apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: mood-analyzer
  labels:
    apps.tanzu.vmware.com/workload-type: dekt-worker
    app.kubernetes.io/part-of: mood-analyzer
spec:
  #source code
  source:
    git:
      url: https://github.com/svrc/mood-analyzer
      ref:
        branch: main
  #data services
  serviceClaims:
  - name: rabbitmq-claim
    ref:
      apiVersion: rabbitmq.com/v1beta1
      kind: RabbitmqCluster
      name: reading-queue