---
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: managed-kubernetes-native
  annotations:
    meta.crossplane.io/maintainer: Stuart Charlton <scharlton@vmware.com
    
spec:
  crossplane:
    version: ">=v1.9"
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-aws
      version: ">=v0.34.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-azure
      version: ">=v0.20.1"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-gcp
      version: ">=v0.22.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
      version: ">=v0.12.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      version: ">=v0.5.0"
